In [2]:
# arrange()
import numpy as np
#start and end limit
np.arange(0,10000)


array([   0,    1,    2, ..., 9997, 9998, 9999], shape=(10000,))

In [3]:
#step value = 2
np.arange(0,10,2)


array([0, 2, 4, 6, 8])

In [4]:
# linspace()

#Generating values between 0 and 10
arr = np.linspace(0,10)
print(arr)
print('Length of arr: ',len(arr))


[ 0.          0.20408163  0.40816327  0.6122449   0.81632653  1.02040816
  1.2244898   1.42857143  1.63265306  1.83673469  2.04081633  2.24489796
  2.44897959  2.65306122  2.85714286  3.06122449  3.26530612  3.46938776
  3.67346939  3.87755102  4.08163265  4.28571429  4.48979592  4.69387755
  4.89795918  5.10204082  5.30612245  5.51020408  5.71428571  5.91836735
  6.12244898  6.32653061  6.53061224  6.73469388  6.93877551  7.14285714
  7.34693878  7.55102041  7.75510204  7.95918367  8.16326531  8.36734694
  8.57142857  8.7755102   8.97959184  9.18367347  9.3877551   9.59183673
  9.79591837 10.        ]
Length of arr:  50


In [5]:
#Number of values = 3
print(np.linspace(0,10,3))


[ 0.  5. 10.]


In [7]:
# zeros()
import numpy as np
#1D
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [ ]:
#2D
np.zeros([2,3])

In [ ]:
# ones()
#1D
np.ones(3)

In [6]:
#2D
np.ones([2,1])

array([[1.],
       [1.]])

In [8]:
# full()
#number=5, value=8
np.full(5,8)


array([8, 8, 8, 8, 8])

In [9]:
#shape=[3,3], value=numpy
np.full([3,3],'numpy')


array([['numpy', 'numpy', 'numpy'],
       ['numpy', 'numpy', 'numpy'],
       ['numpy', 'numpy', 'numpy']], dtype='<U5')

In [10]:
# eye()
#3x3 identity matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [2]:
# random
import numpy as np
#generating 5 random numbers from a uniform distribution
np.random.rand(5)


array([0.95504569, 0.22057416, 0.01387227, 0.87347722, 0.95806296])

In [3]:
#random integer values low=1, high=10, number of values=5
np.random.randint(1,10, size=5)


array([4, 6, 9, 5, 1], dtype=int32)

In [4]:
# two dimensional array can also be created by passing the shape rather than values
#random integer values high=100, shape = (3,5)
x = np.random.randint(100, size=(3, 5))
print(x)
print(type(x))


[[74 95 14  8 97]
 [ 7 93 44 96 15]
 [51 42 22  7  8]]
<class 'numpy.ndarray'>


In [ ]:
# To generate a random number from a predefined set of values present in an array,
# the choice() method can be used
#returns a single random value from the array
x = np.random.choice([9, 3, 7, 5])
print(x)


In [5]:

#returns 3*5 random values from the array
x = np.random.choice([9, 3, 7, 5], size=(3, 5))   # sampling to create an nd-array 
print(x)
print(type(x))


[[9 7 5 7 9]
 [7 7 3 7 5]
 [7 5 5 7 3]]
<class 'numpy.ndarray'>
