In [ ]:
'''Represent the above data in a 10x2 array. In each row, the first element should 
contain day number and second element should contain steps walked.'''

import numpy as np
record = np.array([[1,6012],[2,7079],[3,6886],[4,7230],[5,4598],[6,5564],[7,6971]
,[8,7763],[9,8032],[10,9569]])
record

array([[   1, 6012],
       [   2, 7079],
       [   3, 6886],
       [   4, 7230],
       [   5, 4598],
       [   6, 5564],
       [   7, 6971],
       [   8, 7763],
       [   9, 8032],
       [  10, 9569]])

In [6]:
'''Lee notices that the tracker’s battery dies every day at 7 pm. Lee discovers that 
on an average, he walks 2000 steps every day after 7 pm. Perform an appropriate 
operation on your array to add 2000 steps to all the observations.'''

import numpy as np
record = np.array([[1,6012],[2,7079],[3,6886],[4,7230],[5,4598],[6,5564],[7,6971]
,[8,7763],[9,8032],[10,9569]])

record += [0,2000]
record

array([[    1,  8012],
       [    2,  9079],
       [    3,  8886],
       [    4,  9230],
       [    5,  6598],
       [    6,  7564],
       [    7,  8971],
       [    8,  9763],
       [    9, 10032],
       [   10, 11569]])

In [7]:
'''Write a program that returns the steps walked if the steps walked are more than 
9000.'''
steps = [8012,9079,8886,9230,6598,7564,8971,9763,10032,11569]
steps_arr =np.array(steps)
x= np.where(steps_arr >9000)
print(x)
steps_arr[x]


(array([1, 3, 7, 8, 9]),)


array([ 9079,  9230,  9763, 10032, 11569])

In [8]:
'''Print an array containing steps walked in sorted order.'''

steps = [8012,9079,8886,9230,6598,7564,8971,9763,10032,11569]
steps_arr =np.array(steps)
print("Sorted array",np.sort(steps_arr))

Sorted array [ 6598  7564  8012  8886  8971  9079  9230  9763 10032 11569]
